spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.99.100}:${DB_PORT:5432}/${DB_NAME:iotc}
    username: ${DB_USER:iotc}
    password: ${DB_PASSWORD:iotc}
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults : false
  output:
    ansi:
      enabled: ALWAYS


logging:
  level:
    com.gmos.iotc: ${LOG_LEVEL:DEBUG}

server:
  port: ${TOMCAT_HTTP_PORT_V:8092}