spring:
  application:
    name: "iot-c-collector-ui"
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com.gmos.iotc: ${LOG_LEVEL:DEBUG}

server:
  port: ${TOMCAT_HTTP_PORT_V:8093}

# jaeger
opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    probabilistic-sampler:
      sampling-rate: ${JAEGER_SAMPLING_RATE:1.0} # Where value is between 0.0 (no sampling) and 1.0 (sampling of every request)
    udp-sender:
      host: ${JAEGER_HOST:localhost}
      port: ${JAEGER_PORT:6831}

iot-collector-ui:
  collector-host-name: ${COLLECTOR_HOST_NAME:localhost}
  collector-host-port: ${COLLECTOR_HOST_PORT:8092}