spring:
  application:
    name: iot-c-collector-ui
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com.gmos.iotc: ${LOG_LEVEL:DEBUG}
  ## log format json
  #https://stackoverflow.com/questions/53730449/is-there-a-recommended-way-to-get-spring-boot-to-json-format-logs-with-logback
  #pattern:
  #  console: "{\"time\": \"%d\", \"level\": \"%p\", \"correlation-id\": \"%X{X-Correlation-Id}\", \"source\": \"%logger{63}:%L\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"

server:
  port: ${TOMCAT_HTTP_PORT_V:8093}

# prometheus
management:
  endpoints.web.exposure.include: "info, health, prometheus"
  #  metrics.enable.jvm: false
  metrics.tags:
    instanceHostName: ${HOSTNAME:localhost}
    application: iot-c
    service: iot-c-collector-ui

# jaeger
opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    probabilistic-sampler:
      sampling-rate: ${JAEGER_SAMPLING_RATE:0.0} # Where value is between 0.0 (no sampling) and 1.0 (sampling of every request)
#    udp-sender:
#      host: ${JAEGER_HOST:localhost}
#      port: ${JAEGER_PORT:6831}
    http-sender:
      url: ${JAEGER_HOST_HTTP_URL:http://localhost:14268/api/traces}
    log-spans: ${JAEGER_LOG_SPANS:true}

# grpc client
grpc:
  client:
    collector-grpc-server:
      address: static://${COLLECTOR_HOST_NAME:localhost}:${COLLECTOR_GRPC_PORT:9091}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

iot-collector-ui:
  collector-host-name: ${COLLECTOR_HOST_NAME:localhost}
  collector-host-port: ${COLLECTOR_HOST_PORT:8092}