apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-collector
  labels:
    app: iot-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-collector
  template:
    metadata:
      labels:
        app: iot-collector
        version: latest
    spec:
      containers:
        - image: dgs19/iot-collector:latest
          imagePullPolicy: Always
          name: iot-collector
          ports:
            - containerPort: 8092
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: JAVA_OPTS
              value: "-javaagent:/opentelemetry-javaagent.jar"
            - name: DB_HOST
              value: "iot-postgres-db"
            - name: JAEGER_HOST_HTTP_URL
              #value: "http://jaeger-all-in-one:14268/api/traces"
              value: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"
            - name: JAEGER_SAMPLING_RATE
              value: "1.0"
            - name: "OTEL_SERVICE_NAME"
              value: "collector-otel-name"
            - name: "OTEL_METRICS_EXPORTER"
              value: "none"
            - name: "OTEL_TRACES_EXPORTER"
              value: "jaeger" # logging # jaeger
            - name: "OTEL_EXPORTER_JAEGER_ENDPOINT"
              #value: "http://jaeger-all-in-one:14250"
              #value: "http://jaeger-all-in-one.default.svc.cluster.local:14250"
              value: "http://jaeger-collector.istio-system.svc.cluster.local:14250"
            - name: "OTEL_PROPAGATORS"
              value: "tracecontext,baggage,b3multi"

---
kind: Service
apiVersion: v1
metadata:
  name: iot-collector
  labels:
    app: iot-collector
spec:
  selector:
    app: iot-collector
  type: NodePort
  ports:
    - port: 8092
      name: http
      targetPort: 8092
      nodePort: 30092
