apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-all-in-one
  template:
    metadata:
      labels:
        app: jaeger-all-in-one
        version: "1.31"
    spec:
      containers:
        - image: jaegertracing/all-in-one:1.31
          imagePullPolicy: Always
          name: jaeger-all-in-one
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: "9411"
          ports:
            - containerPort: 9411
            - containerPort: 16686
            - containerPort: 6831
            - containerPort: 14250
---
kind: Service
apiVersion: v1
metadata:
  name: jaeger-all-in-one
spec:
  selector:
    app: jaeger-all-in-one
  ports:
    - name: http-zipkin
      protocol: TCP
      port: 9411
    - name: udp-jaeger-sender
      protocol: UDP
      port: 6831
    - name: http-jaeger-sender
      protocol: TCP
      port: 14268
    - name: http-otel-tcp # accept model.proto
      protocol: TCP
      port: 14250
    - name: http-otel-udp # accept model.proto
      protocol: UDP
      port: 14250


---
kind: Service
apiVersion: v1
metadata:
  name: jaeger-all-in-one-web-ui
spec:
  selector:
    app: jaeger-all-in-one
  type: NodePort
  ports:
    - name: http-web-ui
      port: 16686
      targetPort: 16686
      nodePort: 30094
