version: '3.6'
services:
  postgres-db:
    image: postgres:14.2
    networks:
      - iotc-db
    environment:
      POSTGRES_USER: ${DB_USER:-iotc}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-iotc}
      POSTGRES_DB: ${DB_NAME:-iotc}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-iotc} || exit false"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - db-data:/var/lib/postgresql/data

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.56
    networks:
      - iotc-db
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # Web UI
      - "4317:4317" # traces - accept OpenTelemetry Protocol (OTLP) over gRPC
      - "4318:4318" # traces - accept OpenTelemetry Protocol (OTLP) over HTTP
      - "14268:14268" # accept jaeger.thrift directly from clients
      - "14250:14250" # accept model.proto
      - "14269:14269"
      - "9411:9411" # Zipkin compatible endpoint (optional)

networks:
  iotc-db:

volumes:
  db-data:
