version: '3.6'
services:
  postgres-db:
    image: postgres:14.2
    networks:
      - iotc-db
    environment:
      POSTGRES_USER: ${DB_USER:-iotc}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-iotc}
      POSTGRES_DB: ${DB_NAME:-iotc}
#    ports:
#      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-iotc} || exit false"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - db-data:/var/lib/postgresql/data

  collector:
#    image: dgs19/iot-collector:0.0.2
    image: iot-collector:latest
    networks:
      - iotc-db
      - iotc-ui
    environment:
      LOG_LEVEL: DEBUG
      JAVA_OPTS: "-javaagent:/opentelemetry-javaagent.jar"
      DB_HOST: postgres-db
      JAEGER_HOST_HTTP_URL: http://jaeger-all-in-one:14268/api/traces
      JAEGER_SAMPLING_RATE: 0.0 # # Where value is between 0.0 (no sampling) and 1.0 (sampling of every request)
      OTEL_SERVICE_NAME: collector-otel-name
      OTEL_METRICS_EXPORTER: none # explicitly disable since default is otlp
      OTEL_TRACES_EXPORTER: jaeger # logging # jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger-all-in-one:14250
      OTEL_PROPAGATORS: "tracecontext,baggage,b3multi"

  collector-ui:
#    image: dgs19/iot-collector-ui:0.0.2
    image: iot-collector-ui:latest
    networks:
      - iotc-ui
    environment:
      LOG_LEVEL: DEBUG
      JAVA_OPTS: "-javaagent:/opentelemetry-javaagent.jar"
      COLLECTOR_HOST_NAME: collector
      JAEGER_HOST_HTTP_URL: http://jaeger-all-in-one:14268/api/traces
      JAEGER_SAMPLING_RATE: 0.0 # # Where value is between 0.0 (no sampling) and 1.0 (sampling of every request)
      OTEL_SERVICE_NAME: collector-ui-otel-name
      OTEL_METRICS_EXPORTER: none # explicitly disable since default is otlp
      OTEL_TRACES_EXPORTER: jaeger # logging # jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger-all-in-one:14250
      OTEL_PROPAGATORS: "tracecontext,baggage,b3multi"

    ports:
      - "8093:8093"

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.31
    networks:
      - iotc-db
      - iotc-ui
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - "16686:16686" # Web UI
      - "14250:14250"

networks:
  iotc-db:
  iotc-ui:

volumes:
  db-data:
