version: '3.6'
services:
  postgres-db:
    image: postgres:14.2
    networks:
      - iotc-db
    environment:
      POSTGRES_USER: ${DB_USER:-iotc}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-iotc}
      POSTGRES_DB: ${DB_NAME:-iotc}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-iotc} || exit false"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  iotc-db:

volumes:
  db-data:
