spring:
  application:
    name: collector-kafka-pg
  output:
    ansi:
      enabled: ALWAYS
  kafka.bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}

logging:
  level:
    com.gmos.iotc: ${LOG_LEVEL:DEBUG}
    org.springframework.kafka: ${LOG_LEVEL_KAFKA:INFO}

server:
  port: ${TOMCAT_HTTP_PORT_V:8096}

iot-collector-kafka-pg:
  key1: ${ENV_KEY1:val1}
  kafka-bootstap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
  kafka-username: ${KAFKA_USERNAME:admin}
  kafka-password: ${KAFKA_PASSWORD:admin}
  kafka-topic-replica: ${KAFKA_TOPIC_REPLICA:1}
  kafka-topic-partition: ${KAFKA_TOPIC_PARTITION:3}