spring:
  application:
    name: collector-kafka-pg
  output:
    ansi:
      enabled: ALWAYS
  kafka.bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}

logging:
  level:
    com.gmos.iotc: ${LOG_LEVEL:DEBUG}

server:
  port: ${TOMCAT_HTTP_PORT_V:8096}

iot-collector-kafka-pg:
  key: val1
  kafka-bootstap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}