name: build java app

on:
  push:
    paths:
      - '.github/workflows/01_java_app_gradle.yml'
      - 'resources/dockerfile-assignment-2/java_app/**'
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
      - 'release*'     # Push events to branches matching refs/heads/release_01

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11.0.3
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.3
#    - name: Build with Gradle
#      run: cd resources/dockerfile-assignment-2/java_app/ && ./gradlew build
    - name: Build with Docker
      run: |
        docker version
        cd resources/dockerfile-assignment-2/java_app/
        docker build -t java_app -f Solution_v2.Dockerfile .
