name: test ansible custom action

on: push

jobs:

  ansible1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/ansible
        env:
          VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}
          SERVER_KEY_ID_RSA: ${{ secrets.DEV_SERVER_1_KEY_ID_RSA }}