name: test ansible custom action

on: push

jobs:

  ansible1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/ansible
  #      env:
  #        VAULT_PASS: ${{ secrets.VAULT_PASS }}