name: Vulnerability Scan with Trivy and Dockle

on:

  push:
    paths:
      - '.github/workflows/06_trivy_scan.yml'
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
      - 'release*'     # Push events to branches matching refs/heads/release_01

jobs:

  scan-traefik:
    name: Container image scan traefik
    runs-on: ubuntu-latest
    steps:
    - name: scan traefik:2.4.8
      uses: Azure/container-scan@v0
      with:
        image-name: traefik:2.4.8
      continue-on-error: true  
    - name: scan traefik:2.6.1  
      uses: Azure/container-scan@v0
      with:
        image-name: traefik:2.6.1
      continue-on-error: true    

  scan-postgres:
    name: Container image scan timescale
    runs-on: ubuntu-latest
    steps:
    - name: scan timescaledb:1.7.3-pg12
      uses: Azure/container-scan@v0
      with:
        image-name: timescale/timescaledb:1.7.3-pg12
      continue-on-error: true  
    - name: scan traefik:2.6.1  
      uses: Azure/container-scan@v0
      with:
        image-name: timescale/timescaledb:1.7.5-pg12
      continue-on-error: true    