name: Scan synca images

on:

  push:
    paths:
      - '.github/workflows/06_trivy_scan.yml'
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
      - 'release*'     # Push events to branches matching refs/heads/release_01

jobs:

  scan-traefik:
    name: Container image scan traefik
    runs-on: ubuntu-latest
    steps:
    - name: scan traefik:2.4.8
      uses: Azure/container-scan@v0
      with:
        image-name: traefik:2.4.8
      continue-on-error: true  
    - name: scan traefik:2.6.1  
      uses: Azure/container-scan@v0
      with:
        image-name: traefik:2.6.1
      continue-on-error: true    

  scan-timescale:
    name: Container image scan timescale
    runs-on: ubuntu-latest
    steps:
    - name: scan timescaledb:1.7.3-pg12
      uses: Azure/container-scan@v0
      with:
        image-name: timescale/timescaledb:1.7.3-pg12
      continue-on-error: true  
    - name: scan timescaledb:1.7.5-pg12
      uses: Azure/container-scan@v0
      with:
        image-name: timescale/timescaledb:1.7.5-pg12
      continue-on-error: true
    - name: scan timescaledb:2.2.1-pg12
      uses: Azure/container-scan@v0
      with:
        image-name: timescale/timescaledb:2.2.1-pg12
      continue-on-error: true
    - name: scan timescaledb:2.6.0-pg12
      uses: Azure/container-scan@v0
      with:
        image-name: timescale/timescaledb:2.6.0-pg12
      continue-on-error: true
    - name: scan timescaledb:2.6.0-pg14
      uses: Azure/container-scan@v0
      with:
        image-name: timescale/timescaledb:2.6.0-pg14
      continue-on-error: true
    - name: scan timescaledb:2.6.0-pg14-bitnami
      uses: Azure/container-scan@v0
      with:
        image-name: timescale/timescaledb:2.6.0-pg14-bitnami
      continue-on-error: true

  scan-kafka:
    name: Container image scan kafka
    runs-on: ubuntu-latest
    steps:
    - name: scan wurstmeister/kafka:2.13-2.7.0
      uses: Azure/container-scan@v0
      with:
        image-name: wurstmeister/kafka:2.13-2.7.0
      continue-on-error: true
    - name: scan wurstmeister/kafka:2.13-2.8.1
      uses: Azure/container-scan@v0
      with:
        image-name: wurstmeister/kafka:2.13-2.8.1
      continue-on-error: true  
    - name: scan bitnami/kafka
      uses: Azure/container-scan@v0
      with:
        image-name: bitnami/kafka:3.1.0-debian-10-r50
      continue-on-error: true  