name: build iot-c java apps

on:
  push:
    paths:
      - '.github/workflows/07_iotc_build.yml'
      - 'resources/iot-c/**'
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
      - 'release*'     # Push events to branches matching refs/heads/release_01

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up temurin JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME_GERASSIMOS }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_DGS19 }}
    - name: Build with Gradle
      run: |
        docker version
        cd resources/iot-c
        ./gradlew :collector-a-to-c:dockerPushTag1 -P DOCKER_USERNAME=dgs19 -P IOTC_TAG=latest
        ./gradlew :collector-ui:dockerPushTag1 -P DOCKER_USERNAME=dgs19 -P IOTC_TAG=latest
        ./gradlew :collector:dockerPushTag1 -P DOCKER_USERNAME=dgs19 -P IOTC_TAG=latest