name: build iot-c-go go apps

on:
  push:
    paths:
      - '.github/workflows/08_iotc_go_build.yml'
      - 'resources/iot-c-go/**'
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
      - 'release*'     # Push events to branches matching refs/heads/release_01

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
        cache: true
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME_GERASSIMOS }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_DGS19 }}
    - name: Build with make
      run: |
        docker version
        cd resources/iot-c-go
        echo "start make build"
        make build
        echo "start make build_docker"
        make build_docker
